Create functional option for ctx.SetCookie
go-macaron/macaron pull request #208
Opened 2020-10-24 19:44 UTC by zeripath

Allowing `func(*http.Cookie)` to be passed into the SetCookie call will allow us to extend SetCookie to set the SameSite attribute easily.

(This PR also does some slight cleanup to context.go fixing minor lint issues.)

2020-11-11 19:51 UTC, 6543 commented
@unknwon can you have a look at it?

it also would cover #206 ... but in a more general way :)

2020-11-12 06:53 UTC, unknwon requested changes
Thanks for the PR!

Can we also have some tests to cover uses of these helpers?

Likely will be added to here:

https://github.com/go-macaron/macaron/blob/d229aed598800fac0be5261b1b14e4bf9b4e6333/context_test.go#L206-L212

2020-11-12 06:53 UTC, unknwon commented on context.go
> +// Copyright 2020 The Gitea Authors
I do not think this is an appropriate addition unless this is a maintained fork version.

Disclaimer: I am not good at legal terms.

2020-11-12 06:53 UTC, unknwon commented on context.go
> +// Invoke implements inject.FastInvoker - in the context of a func(ctx *Context) this simply calls the function
```suggestion
// Invoke implements inject.FastInvoker which simplifies calls of `func(ctx *Context)` function.
```

2020-11-12 06:53 UTC, unknwon commented on cookie/helper.go
> +// cookie contains helper functions for setting cookie values
```suggestion
// Package cookie contains helper functions for setting cookie values.
package cookie

import (
	"net/http"
	"time"
)
```

2020-11-12 06:53 UTC, unknwon commented on cookie/helper.go
> +// Copyright 2020 The Gitea Authors
```suggestion
```

2020-11-12 06:53 UTC, unknwon commented on context.go
> +// Copyright 2020 The Gitea Authors
```suggestion
```

2020-11-12 18:35 UTC, 6543 commented on context_test.go
> +					called = false
```suggestion
					called = true
```

2020-11-12 18:41 UTC, 6543 commented
@unknwon I'ts ready again :)

2020-11-13 12:00 UTC, unknwon approved these changes
Thanks for the follow up!

2020-11-13 12:00 UTC, merged

2020-11-13 12:01 UTC, unknwon commented
https://github.com/go-macaron/macaron/releases/tag/v1.4.0 has been published for this merge.